MuellesObrero/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MuellesObrero.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^accounts/', include('authentication.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('database.urls')),
    # url(r'^.*$', RedirectView.as_view(url='/', permanent=False), name='index')
)

database/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
	url(r'reports/differences/products/$', 'database.views.product_diff', name='product_diff'),
	url(r'reports/differences/providers/$', 'database.views.provider_diff', name='provider_diff'),
	url(r'reports/differences/storage/$', 'database.views.storage_diff', name='storage_diff'),
	url(r'reports/expenses/$', 'database.views.expenses', name='expenses'),
	url(r'reports/$', 'database.views.reports', name='reports'),
	url(r'product/(?P<id>\w+\W*\w*)/$', 'database.views.product', name='product'),
	url(r'tool/(?P<id>\w+\W*\w*)/$', 'database.views.tool', name='tool'),
	url(r'tools/$', 'database.views.tools', name='tools'),
	url(r'inputs/$', 'database.views.inputs', name='inputs'),
	url(r'outputs/$', 'database.views.outputs', name='outputs'),
	url(r'lendings/$', 'database.views.lendings', name='lendings'),
	url(r'shopping/$', 'database.views.shopping', name='shopping'),
	url(r'providers/$', 'database.views.providers', name='providers'),
	url(r'brands/$', 'database.views.brands', name='brands'),
	url(r'organizations/$', 'database.views.organizations', name='organizations'),
	url(r'appliances/$', 'database.views.appliances', name='appliances'),
	url(r'percentages/$', 'database.views.percentages', name='percentages'),
	url(r'registry/$', 'database.views.registry', name='registry'),
	url(r'settings/$', 'database.views.settings', name='settings'),
	url(r'settings/backup/$', 'database.views.backup', name='backup'),
	url(r'^$', 'database.views.dashboard', name='dashboard'),
)

database/forms.py
from django import forms
from django.utils.encoding import (
    force_str, force_text, python_2_unicode_compatible,
)
from django.utils.html import conditional_escape, format_html


from django.forms.utils import flatatt
from django.utils.safestring import mark_safe

from models import Product, Tool, Provider, Appliance, Brand, Lending, Input_Product, Output_Product, Lending_Product, Order_Product, Configuration, BackupManager, Percentage, Organization

from datetime import datetime

class DateInput(forms.DateInput):
    input_type = 'date'

class ProductSelect(forms.widgets.Select):
    def render_option(self, selected_choices, option_value, option_label):
        if option_value is None:
            option_value = ''
        option_value = force_text(option_value)
        if option_value in selected_choices:
            selected_html = mark_safe(' selected="selected"')
            if not self.allow_multiple_selected:
                # Only allow for a single selection.
                selected_choices.remove(option_value)
        else:
            selected_html = ''
        return format_html('<option value="{}" provider="{}" price="{}" discount="{}" {}>{}</option>',
                           option_value,
                           self.choices.queryset.get(code=option_value).provider.id,
                           self.choices.queryset.get(code=option_value).price,
                           self.choices.queryset.get(code=option_value).discount,
                           selected_html,
                           force_text(option_label).encode("ascii", "ignore"))

class Datalist(forms.widgets.Select):
    def render(self, name, value, attrs=None, choices=()):
        if value is None:
            value = ''
        datalist_attrs = attrs
        final_attrs = self.build_attrs(attrs, name=name)
        final_attrs["list"] = final_attrs.pop("id")
        if value != '':
            if name == "brand":
                final_attrs["value"] = Brand.objects.get(id=value).name
            elif name == "provider":
                final_attrs["value"] = Provider.objects.get(id=value).name
        output = [format_html('<input{} />', flatatt(final_attrs)), format_html('<datalist{}>', flatatt(datalist_attrs))]
        options = self.render_options(choices, [value])
        if options:
            output.append(options)
        output.append('</datalist>')
        return mark_safe('\n'.join(output))

    def render_option(self, selected_choices, option_value, option_label):
        if option_value is None:
            option_value = ''
        if option_value == "":
            option_label = ""
        option_value = force_text(option_value)
        return format_html('<option value="{}"></option>',
                           force_text(option_label))

class ProductForm(forms.ModelForm):
    code = forms.CharField(max_length=30, label='Codigo')
    brand = forms.ModelChoiceField(queryset=Brand.objects.all(), required=False, label="Marca", widget=Datalist())
    provider = forms.ModelChoiceField(queryset=Provider.objects.all(), required=False, label="Proveedor", widget=Datalist())
    name = forms.CharField(max_length=200, label='Nombre')
    description = forms.CharField(max_length=255, label='Descripcion', required=False)
    appliance = forms.ModelMultipleChoiceField(queryset=Appliance.objects.all(), required=False, label="Aplicacion")
    price = forms.DecimalField(max_digits=9, decimal_places=2, label='Precio de lista', required=True, min_value=0, initial=0)
    discount = forms.DecimalField(max_digits=9, decimal_places=2, label='Descuento', required=False, initial=0, min_value=0, max_value=100)
    real_price = forms.DecimalField(max_digits=9, decimal_places=2, label='Precio real', required=False, initial=0, min_value=0, widget=forms.widgets.NumberInput(attrs={'disabled':'disabled'}))
    in_used = forms.IntegerField(label='Obsoletas', initial=0, min_value=0)
    in_stock = forms.IntegerField(label='Propias', initial=0, min_value=0)
    stock_tobe = forms.IntegerField(label='Stock propias', initial=0, min_value=0)
    in_consignment = forms.IntegerField(label='Consignacion', initial=0, min_value=0)
    consignment_tobe = forms.IntegerField(label='Stock consignacion', initial=0, min_value=0)

    class Meta:
        model = Product
        fields = [
            "code",
            "brand",
            "provider",
            "name",
            "description",
            "appliance",
            "price",
            "discount",
            "real_price",
            "in_used",
            "in_stock",
            "stock_tobe",
            "in_consignment",
            "consignment_tobe",
            ]

class ToolForm(forms.ModelForm):
    code = forms.CharField(max_length=30, label='Codigo')
    name = forms.CharField(max_length=200, label='Nombre')
    description = forms.CharField(max_length=255, label='Descripcion', required=False)
    condition = forms.CharField(max_length=255, label='Condicion', required=False)
    amount = forms.IntegerField(initial=0, label='Cantidad', required=True)

    class Meta:
        model = Tool
        fields = "__all__"

class ProductInputForm(forms.ModelForm):
    date = forms.DateField(widget=DateInput(), label='Fecha', initial=datetime.now())
    invoice_number = forms.CharField(max_length=100, label='Numero de Factura', required=False)
    filter_search = forms.CharField(max_length=100, label='Buscar producto')
    product = forms.ModelMultipleChoiceField(queryset=Product.objects.all(), required=False, label="Seleccionar productos", widget=ProductSelect(attrs={"size":"10"}))
    amount = forms.IntegerField(label='Cantidad', initial=1)
    price = forms.DecimalField(max_digits=9, decimal_places=2, label='Precio de lista', initial=0)
    storage = forms.ChoiceField(label='Almacen', choices=Product.STORAGE_CHOICES)
    provider = forms.ModelChoiceField(queryset=Provider.objects.all(), required=False, label="Proveedor")

    class Meta:
        model = Input_Product
        fields = ['date', 'invoice_number', 'storage', 'provider', 'filter_search', 'product', 'amount', 'price']

class ProductOutputForm(forms.ModelForm):
    date = forms.DateField(widget=DateInput(), label='Fecha', initial=datetime.now())
    employee = forms.CharField(max_length=100, label='Empleado')
    destination = forms.CharField(max_length=100, label='Destino')
    organization = forms.ModelChoiceField(queryset=Organization.objects.all(), required=False, label="Organizacion")
    filter_search = forms.CharField(max_length=100, label='Buscar producto')
    product_consignment = forms.ModelMultipleChoiceField(queryset=Product.objects.filter(in_consignment__gt=0), required=False, label="Seleccionar productos", widget=ProductSelect(attrs={"size":"10"}))
    product_stock = forms.ModelMultipleChoiceField(queryset=Product.objects.filter(in_stock__gt=0), required=False, label="Seleccionar productos", widget=ProductSelect(attrs={"size":"10"}))
    product_used = forms.ModelMultipleChoiceField(queryset=Product.objects.filter(in_used__gt=0), required=False, label="Seleccionar productos", widget=ProductSelect(attrs={"size":"10"}))
    amount = forms.IntegerField(label='Cantidad', initial=1)
    storage = forms.ChoiceField(label='Almacen', choices=Product.STORAGE_CHOICES)
    provider = forms.ModelChoiceField(queryset=Provider.objects.all(), required=False, label="Proveedor")

    class Meta:
        model = Output_Product
        fields = ['date', 'employee', 'destination', 'organization', 'storage', 'provider', 'filter_search', 'product_consignment', 'product_stock', 'product_used', 'amount']

class ProductLendingForm(forms.ModelForm):
    date = forms.DateField(widget=DateInput(), label='Fecha', initial=datetime.now())
    employee = forms.CharField(max_length=100, label='Empleado')
    destination = forms.CharField(max_length=100, label='Destino')
    filter_search = forms.CharField(max_length=100, label='Buscar producto')
    product_consignment = forms.ModelMultipleChoiceField(queryset=Product.objects.filter(in_consignment__gt=0), required=False, label="Seleccionar productos", widget=ProductSelect(attrs={"size":"10"}))
    product_stock = forms.ModelMultipleChoiceField(queryset=Product.objects.filter(in_stock__gt=0), required=False, label="Seleccionar productos", widget=ProductSelect(attrs={"size":"10"}))
    product_used = forms.ModelMultipleChoiceField(queryset=Product.objects.filter(in_used__gt=0), required=False, label="Seleccionar productos", widget=ProductSelect(attrs={"size":"10"}))
    amount = forms.IntegerField(label='Cantidad', initial=1)
    storage = forms.ChoiceField(label='Almacen', choices=Product.STORAGE_CHOICES)
    provider = forms.ModelChoiceField(queryset=Provider.objects.all(), required=False, label="Proveedor")

    class Meta:
        model = Lending
        fields = ['date', 'employee', 'destination', 'storage', 'provider', 'filter_search', 'product_consignment', 'product_stock', 'product_used', 'amount']

class ToolLendingForm(forms.ModelForm):
    date = forms.DateField(widget=DateInput(), label='Fecha', initial=datetime.now())
    employee = forms.CharField(max_length=100, label='Empleado')
    destination = forms.CharField(max_length=100, label='Destino')
    tool_filter_search = forms.CharField(max_length=100, label='Buscar herramienta')
    tool = forms.ModelMultipleChoiceField(queryset=Tool.objects.all(), required=False, label="Seleccionar herramienta", widget=forms.widgets.Select(attrs={"size":"10"}))
    amount = forms.IntegerField(label='Cantidad', initial=1)

    class Meta:
        model = Lending
        fields = ['date', 'employee', 'destination', 'tool_filter_search', 'tool', 'amount']

class ProviderForm(forms.ModelForm):
    name = forms.CharField(max_length=100, label='Nombre')

    class Meta:
        model = Provider
        fields = "__all__"

class UpdateProviderForm(forms.ModelForm):
    id = forms.IntegerField(widget = forms.HiddenInput)

templates/pages/accounts.html
{% extends "layouts/base.html" %}

{% block page_title %}
<title>Muelles Obrero</title>
{% endblock %}

{% block page_top %}
{% include 'sections/navbar.html' %}
{% endblock %}

{% block header %}
<div style="padding-top: 60px;"></div>
{% endblock %}

{% block site_wrapper %}
<div style="margin: auto;max-width: 1200px">
	<div class="col-md-12">
	    <div class="row">
	        <h2>
	            <div class="col-sm-10">Usuarios</div>
	            <div class="col-sm-1">
	                <p data-placement="top" data-toggle="tooltip" title="Agregar nuevo usuario"><button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#new"><i class="fa fa-plus-square"></i></button></p>
	            </div>
	            <div class="col-sm-1">
	                <p data-placement="top" data-toggle="tooltip" title="Eliminar usuarios seleccionados"><button type="button" class="btn btn-danger btn-lg btn-block" data-toggle="modal" data-target="#delete"><i class="fa fa-trash"></i></button></p>
	            </div>
	        </h2>
	    </div>
	    <div class="row">
        <div class="table-responsive">
        	<table id="mytable" class="table table-bordred table-striped">
                <thead>
                	<th><input type="checkbox" id="checkall" /></th>
                    <th>Usuario</th>
                    <th>Nombre</th>
                    <th>Apellidos</th>
                    <th>Email</th>
                    <th style="text-align: center;">Admin</th>
                    <th style="text-align: center;">Modificar</th>
                    <th style="text-align: center;">Eliminar</th>
                </thead>
		    	<tbody>
		    		{% for user in users %}
		    		<tr>
					    <td><input type="checkbox" class="checkthis" value="{{ user.id }}" /></td>
					    <td>{{ user.username }}</td>
					    <td>{{ user.first_name }}</td>
					    <td>{{ user.last_name }}</td>
					    <td>{{ user.email }}</td>
					    {% if user.is_superuser %}
					    <td align="center"><i class="fa fa-check"></td>
					    {% else %}
					    <td align="center"><i class="fa fa-times"></td>
					    {% endif %}
					    <td align="center"><p data-placement="top" data-toggle="tooltip" title="Modificar"><button class="btn btn-success" data-title="Edit" data-toggle="modal" data-target="#edit{{ user.id }}" ><span class="glyphicon glyphicon-pencil"></span></button></p></td>
					    <td align="center"><p data-placement="top" data-toggle="tooltip" title="Eliminar"><button class="btn btn-danger" data-title="Delete" data-toggle="modal" data-target="#delete{{ user.id }}" ><span class="glyphicon glyphicon-trash"></span></button></p></td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
        </div>
    </div>
</div>
<div class="modal fade" id="new" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
        <h4 class="modal-title custom_align">Nuevo Usuario</h4>
    </div>
    <form class="form-horizontal" action="" autocomplete="off" method="POST">
        {% csrf_token %}
        <input type="hidden" name="action" value="CREATE">
        <div class="modal-body">
            {% for field in form %}
            <div class="form-group {% if field.errors %}has-error{% endif %}">
                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-10">
                    {{ field }}
                    {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-ok-sign"></span>Agregar</button>
            <button type="button" class="btn btn-default btn-lg" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancelar</button>
        </div>
    </form>
</div>
<div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
        <h4 class="modal-title custom_align">Borrar los usuarios seleccionados</h4>
    </div>
    <form class="form-horizontal" action="" method="POST" id="multi-delete">
        {% csrf_token %}
        <input type="hidden" name="user_id" value="">
        <input type="hidden" name="action" value="DELETE">
        <div class="modal-body">
            <div class="alert alert-danger"><span class="glyphicon glyphicon-warning-sign"></span> Esta seguro de eliminar estos usuarios de la base de datos?</div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-danger btn-lg" ><span class="glyphicon glyphicon-ok-sign"></span> Eliminar</button>
            <button type="button" class="btn btn-default btn-lg" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancelar</button>
        </div>
    </form>
</div>
{% for user_id, form in user_forms.items %}
<div class="modal fade" id="edit{{ user_id }}" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
        <h4 class="modal-title custom_align">Actualizar usuario</h4>
    </div>
    <form class="form-horizontal" action="" autocomplete="off" method="POST">
        {% csrf_token %}
        <input type="hidden" name="action" value="UPDATE">
        <div class="modal-body">
            {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-10">{{ field }}</div>
            </div>
            {% endfor %}
            <input id="id_id" name="id" type="hidden" value="{{ user_id }}">
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-success btn-lg"><span class="glyphicon glyphicon-ok-sign"></span> Guardar</button>
            <button type="button" class="btn btn-default btn-lg" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancelar</button>
        </div>
    </form>
</div>
<div class="modal fade" id="delete{{ user_id }}" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
        <h4 class="modal-title custom_align">Borrar el usuario: {{ user_id }}</h4>
    </div>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="hidden" name="user_id" value='["{{ user_id }}"]'>
        <input type="hidden" name="action" value="DELETE">
        <div class="modal-body">
            <div class="alert alert-danger"><span class="glyphicon glyphicon-warning-sign"></span> Esta seguro de eliminar este usuario de la base de datos?</div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-danger btn-lg" ><span class="glyphicon glyphicon-ok-sign"></span> Eliminar</button>
            <button type="button" class="btn btn-default btn-lg" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancelar</button>
        </div>
    </form>
</div>
{% endfor %}
{% endblock %}

{% block notifications %}
{% include 'sections/notifications.html' %}
{% endblock %}

{% block footer %}
{% include 'sections/footer.html' %}
{% endblock %}

templates/pages/dashboard.html
{% extends "layouts/base.html" %}

{% block page_title %}
<title>Muelles Obrero</title>
{% endblock %}

{% block page_top %}
{% include 'sections/navbar.html' %}
{% endblock %}

{% block header %}
<div style="padding-top: 60px;"></div>
{% endblock %}

{% block sidebar %}
{% include 'sections/sidebar.html' %}
{% endblock %}

{% block site_wrapper %}
{% if dashboard_active %}
	{% if filter_active %}
	{% include 'sections/productTable.html' %}
	{% endif %}
	{% if tools_active %}
	{% include 'sections/toolTable.html' %}
	{% endif %}
	{% if inputs_active %}
	{% include 'sections/inputTable.html' %}
	{% endif %}
	{% if outputs_active %}
	{% include 'sections/outputTable.html' %}
	{% endif %}
	{% if lendings_active %}
	{% include 'sections/lendingTable.html' %}
	{% endif %}
	{% if shopping_active %}
	{% include 'sections/shoppingTable.html' %}
	{% endif %}
	{% if providers_active %}
	{% include 'sections/providerTable.html' %}
	{% endif %}
	{% if brands_active %}
	{% include 'sections/brandTable.html' %}
	{% endif %}
	{% if appliances_active %}
	{% include 'sections/applianceTable.html' %}
	{% endif %}
	{% if percentages_active %}
	{% include 'sections/percentageTable.html' %}
	{% endif %}
	{% if organizations_active %}
	{% include 'sections/organizationTable.html' %}
	{% endif %}
	{% if registry_active %}
	{% include 'sections/registryTable.html' %}
	{% endif %}
{% endif %}
{% if reports_active %}
	{% if statistics_active %}
	{% include 'sections/statisticsChart.html' %}
	{% endif %}
	{% if expenses_active %}
	{% include 'sections/expensesReport.html' %}
	{% endif %}
	{% if product_diff_active %}
	{% include 'sections/productDiffTable.html' %}
	{% endif %}
	{% if provider_diff_active %}
	{% include 'sections/providerDiffTable.html' %}
	{% endif %}
	{% if storage_diff_active %}
	{% include 'sections/storageDiffTable.html' %}
	{% endif %}
{% endif %}
{% endblock %}

{% block notifications %}
{% include 'sections/notifications.html' %}
{% endblock %}

{% block popup %}
<!-- <div class="popup"></div> -->

<div class="modal fade" id="popup" tabindex="-1" aria-hidden="true" data-focus-on="input:first" style="display: none;">
    <div class="modal-header">
        <h4 class="modal-title title">Inconsistencia en el precio</h4>
    </div>
    <div class="modal-body">
        <p class="content"></p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-success ok" data-dismiss="modal"><span class="glyphicon glyphicon-ok-sign"></span> Aceptar</button>
        <button type="button" class="btn btn-danger cancel" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancelar</button>
    </div>
</div>
{% endblock %}

{% block footer %}
{% include 'sections/footer.html' %}
{% endblock %}

templates/pages/dialog.html
{% extends "layouts/iframe.html" %}

{% block page_title %}
<title>Muelles Obrero</title>
{% endblock %}

{% block site_wrapper %}
{% if object_type == "Product" %}
	{% include 'sections/productForm.html' %}
{% elif object_type == "Tool" %}
	{% include 'sections/toolForm.html' %}
{% endif %}
{% endblock %}

templates/pages/login.html
{% extends "layouts/base.html" %}

{% block page_title %}
<title>Muelles Obrero</title>
{% endblock %}


{% block site_wrapper %}
<div class="row main">
	<div>	
	    <form class="onl_loginForm" action="" autocomplete="off" method="POST">
	    	{% csrf_token %}
			<h1>Bienvenido! </h1>

			<div class="input-group">
				<span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
				<input type="text" class="form-control" name="username" placeholder="Username">
			</div>
			<span class="help-block"></span>
								
			<div class="input-group">
				<span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
				<input  type="password" class="form-control" name="password" placeholder="Password">
			</div>
            <span class="help-block"></span>

			{% if next %}
				<input type="hidden" name="next" value="{{ next }}" />
			{% else %}
				<input type="hidden" name="next" value="/" />
			{% endif %}
			<button class="btn btn-lg btn-primary btn-block" type="submit"><i class="fa fa-sign-in"></i> Entrar</button>
			<p class="onl_forgotPwd">
				<a href="#">Olvidaste tu password?</a>
			</p>
		</form>
	</div>
</div>
<div style="position: fixed;top: 20%;left: 50%;margin-top: -100px;margin-left: -100px;z-index: 10;">
	<img src="/static/img/giphy.gif" width="100">
</div>
{% endblock %}