MuellesObrero/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MuellesObrero.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^accounts/', include('authentication.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('database.urls')),
    # url(r'^.*$', RedirectView.as_view(url='/', permanent=False), name='index')
)

database/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
	url(r'reports/differences/products/$', 'database.views.product_diff', name='product_diff'),
	url(r'reports/differences/providers/$', 'database.views.provider_diff', name='provider_diff'),
	url(r'reports/differences/storage/$', 'database.views.storage_diff', name='storage_diff'),
	url(r'reports/expenses/$', 'database.views.expenses', name='expenses'),
	url(r'reports/$', 'database.views.reports', name='reports'),
	url(r'product/(?P<id>\w+\W*\w*)/$', 'database.views.product', name='product'),
	url(r'tool/(?P<id>\w+\W*\w*)/$', 'database.views.tool', name='tool'),
	url(r'tools/$', 'database.views.tools', name='tools'),
	url(r'inputs/$', 'database.views.inputs', name='inputs'),
	url(r'outputs/$', 'database.views.outputs', name='outputs'),
	url(r'lendings/$', 'database.views.lendings', name='lendings'),
	url(r'shopping/$', 'database.views.shopping', name='shopping'),
	url(r'providers/$', 'database.views.providers', name='providers'),
	url(r'brands/$', 'database.views.brands', name='brands'),
	url(r'organizations/$', 'database.views.organizations', name='organizations'),
	url(r'appliances/$', 'database.views.appliances', name='appliances'),
	url(r'percentages/$', 'database.views.percentages', name='percentages'),
	url(r'registry/$', 'database.views.registry', name='registry'),
	url(r'settings/$', 'database.views.settings', name='settings'),
	url(r'settings/backup/$', 'database.views.backup', name='backup'),
	url(r'^$', 'database.views.dashboard', name='dashboard'),
)

database/models.py
from django.contrib import admin
from django.db import models
# from lib.email_client import send_email
import os
import shutil
import datetime

class Appliance(models.Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name

    def products_related(self):
        products = Product.objects.filter(appliance=self)
        return len(products)

class Provider(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(blank=True, null=True)

    def __unicode__(self):
        return self.name

    def products_related(self):
        products = Product.objects.filter(provider=self)
        return len(products)

class Brand(models.Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name

    def products_related(self):
        products = Product.objects.filter(brand=self)
        return len(products)

class Classification(models.Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name

    def products_related(self):
        products = Product.objects.filter(classification=self)
        return len(products)

class Percentage(models.Model):
    max_price_limit = models.DecimalField(max_digits=9, decimal_places=2)
    percentage_1 = models.DecimalField(max_digits=9, decimal_places=2)
    percentage_2 = models.DecimalField(max_digits=9, decimal_places=2)
    percentage_3 = models.DecimalField(max_digits=9, decimal_places=2)

    def __unicode__(self):
        return self.max_price_limit

    def products_related(self):
        products = Product.objects.filter(percentage=self)
        return len(products)

class Tool(models.Model):
    code = models.CharField(max_length=30, primary_key=True)
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=255, null=True, blank=True)
    condition = models.CharField(max_length=255, null=True, blank=True)
    amount = models.IntegerField()

    def __unicode__(self):
        return self.code+" - "+self.name+" - "+self.description

class Product(models.Model):
    STORAGE_CHOICES = (
        ('C', 'Consignacion'),
        ('S', 'Propias'),
        ('U', 'Obsoletas'),
    )
    code = models.CharField(max_length=30, primary_key=True)
    brand = models.ForeignKey(Brand, null=True, blank=True)
    provider = models.ForeignKey(Provider, null=True, blank=True)
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=255, null=True, blank=True)
    appliance = models.ManyToManyField(Appliance, blank=True)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    discount = models.DecimalField(max_digits=9, decimal_places=2)
    #classification = models.ForeignKey(Classification, null=True, blank=True)
    in_used = models.IntegerField()
    in_stock = models.IntegerField()
    in_consignment = models.IntegerField()
    stock_tobe =models.IntegerField()
    consignment_tobe =models.IntegerField()

    def __str__(self):
        return self.code+" - "+self.name.encode('utf8')+" - "+self.description

    def __unicode__(self):
        return self.code+" - "+self.name+" - "+self.description

class Input(models.Model):
    date = models.DateTimeField()
    invoice_number = models.CharField(max_length=30, null=True, blank=True)
    storage = models.CharField(max_length=1, choices=Product.STORAGE_CHOICES)

    def __init__(self, *args, **kwargs):
        super(Input, self).__init__(*args, **kwargs)
        self.type = "Input"

class Organization(models.Model):
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name

class Output(models.Model):
    date = models.DateTimeField()
    employee = models.CharField(max_length=100)
    destination = models.CharField(max_length=100)
    organization = models.ForeignKey(Organization, null=True, blank=True)
    storage = models.CharField(max_length=1, choices=Product.STORAGE_CHOICES)

    def __init__(self, *args, **kwargs):
        super(Output, self).__init__(*args, **kwargs)
        self.type = "Output"

class Input_Product(models.Model):
    input_reg = models.ForeignKey(Input)
    product = models.ForeignKey(Product)
    amount = models.IntegerField()
    price = models.DecimalField(max_digits=9, decimal_places=2)

class Output_Product(models.Model):
    output_reg = models.ForeignKey(Output)
    product = models.ForeignKey(Product)
    amount = models.IntegerField()
    price = models.DecimalField(max_digits=9, decimal_places=2)

class Lending(models.Model):
    date = models.DateTimeField()
    employee = models.CharField(max_length=100)
    destination = models.CharField(max_length=100)
    storage = models.CharField(max_length=1, choices=Product.STORAGE_CHOICES)
    returned = models.BooleanField(default=False)
    returned_date = models.DateTimeField(null=True)

    def __init__(self, *args, **kwargs):
        super(Lending, self).__init__(*args, **kwargs)
        self.type = "Lending"

class Lending_Product(models.Model):
    lending = models.ForeignKey(Lending)
    product = models.ForeignKey(Product)
    amount = models.IntegerField()
    returned_amount = models.IntegerField()

class Lending_Tool(models.Model):
    lending = models.ForeignKey(Lending)
    tool = models.ForeignKey(Tool)
    amount = models.IntegerField()
    returned_amount = models.IntegerField()

class Order(models.Model):
    STATUS_PENDING = 'P'
    STATUS_ASKED = 'A'
    STATUS_CANCELED = 'C'
    STATUS_RECEIVED = 'R'
    STATUS_CHOICES = (
        (STATUS_PENDING, 'Por pedir'),
        (STATUS_ASKED, 'Pedido'),
        (STATUS_CANCELED, 'Cancelado'),
        (STATUS_RECEIVED, 'Recibido'),
    )
    date = models.DateTimeField(auto_now_add=True)
    provider = models.ForeignKey(Provider)
    claimant = models.CharField(max_length=100, null=True, blank=True)

class Order_Product(models.Model):
    order = models.ForeignKey(Order)
    product = models.ForeignKey(Product)
    amount = models.IntegerField()
    organization = models.ForeignKey(Organization, null=True, blank=True)
    storage = models.CharField(max_length=1, choices=Product.STORAGE_CHOICES, null=True, blank=True)
    status = models.CharField(max_length=1, choices=Order.STATUS_CHOICES, null=True)
    received_date = models.DateTimeField(null=True)

class Configuration(models.Model):
    sender_email = models.EmailField(null=True)
    password = models.CharField(max_length=30, null=True)
    receiver_email = models.EmailField(null=True)
    mailOnPriceChange = models.BooleanField(default=True)
    mailOnNegativeValues = models.BooleanField(default=True)
    # destination del sistema para enviar un correo de adgoritmo para mi hermoso amorcito te amo te amo :*
    # la longitud de mi inteligencia va a ayudar a mi papito clo voy a ayudar siempre

class ProductAdmin(admin.ModelAdmin):
    pass

class InputProductAdmin(admin.ModelAdmin):
    pass

class InputAdmin(admin.ModelAdmin):
    pass

admin.site.register(Product, ProductAdmin)
admin.site.register(Input_Product, InputProductAdmin)
admin.site.register(Input, InputAdmin)

class BackupManager(object):

    # DIRECTORY = os.path.join(os.getcwd(), "backups")# if settings.DEBUG else "C:\\MODB\\backups/"
    DIRECTORY = "C:\\MODB\\backups/"

    def get_current_db(self):
        #if settings.DEBUG:
        # return os.path.join(os.getcwd(), "db.sqlite3")
        #else:
        return "C:\\MODB\\db.sqlite3"

    def get_backups(self):
        backups = []
        for db in os.listdir(BackupManager.DIRECTORY):
            if len(db) == 24 and db.endswith(".sqlite3") and db.startswith("db") and db[2:-8].isdigit():
                formatted_date = db[2:-8][:4]+"-"+db[2:-8][4:6]+"-"+db[2:-8][6:8]+" "+db[2:-8][8:10]+":"+db[2:-8][10:12]+":"+db[2:-8][12:14]
                backups.append((db, formatted_date))
        return backups

    def create_backup(self):
        current_db = self.get_current_db()
        new_db = os.path.join(BackupManager.DIRECTORY, "db"+datetime.datetime.now().strftime('%Y%m%d%H%M%S')+".sqlite3")
        shutil.copy(current_db, new_db)

    def restore_backup(self, backup_file):
        current_db = self.get_current_db()
        new_db = os.path.join(BackupManager.DIRECTORY, backup_file)
        shutil.copy(new_db, current_db)

    def delete_backup(self, backup_file):
        os.remove(os.path.join(BackupManager.DIRECTORY, backup_file))

    # def send_backup(self, backup_file):
    #     conf = Configuration.objects.all()[0]
    #     return conf.receiver_email and send_email(conf.receiver_email, "Respaldo de la Base de Datos", "", files=[backup_file])

    def upload_backup(self, file):
        pass

templates/sections/brandTable.html
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <div class="row">
        <h2>
            {% if request.user.is_superuser %}
            <div class="col-sm-10">
            {% else %}
            <div class="col-sm-12">
            {% endif %}
                Marcas
            </div>
            {% if request.user.is_superuser %}
            <div class="col-sm-1">
                <p data-placement="top" data-toggle="tooltip" title="Eliminar marcas seleccionadas"><button type="button" class="btn btn-danger btn-lg btn-block" data-toggle="modal" data-target="#delete"><i class="fa fa-trash"></i></button></p>
            </div>
            <div class="col-sm-1">
                <p data-placement="top" data-toggle="tooltip" title="Agregar nueva marcas"><button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#new"><i class="fa fa-plus-square"></i></button></p>
            </div>
            {% endif %}
        </h2>
    </div>
    <div class="row">
    <div class="table-responsive">
        <table class="table table-bordred table-striped">
            <thead>
                {% if request.user.is_superuser %}
                <th><input type="checkbox" id="checkall" /></th>
                {% endif %}
                <th>Nombre</th>
                <th>Refacciones</th>
                {% if request.user.is_superuser %}
                <th style="text-align: center;">Actualizar</th>
                <th style="text-align: center;">Eliminar</th>
                {% endif %}
            </thead>
            <tbody>
                {% for brand in brands %}
                <tr>
                    {% if request.user.is_superuser %}
                    <td><input type="checkbox" class="checkthis" value="{{ brand.id }}" /></td>
                    {% endif %}
                    <td>{{ brand.name }}</td>
                    <td>{{ brand.products_related }}</td>
                    {% if request.user.is_superuser %}
                    <td align="center"><p data-placement="top" data-toggle="tooltip" title="Actualizar {{ brand.name }}"><button class="btn btn-success" data-title="Edit" data-toggle="modal" data-target="#edit{{ brand.id }}" ><span class="glyphicon glyphicon-pencil"></span></button></p></td>
                    <td align="center"><p data-placement="top" data-toggle="tooltip" title="Eliminar {{ brand.name }}"><button class="btn btn-danger" data-title="Delete" data-toggle="modal" data-target="#delete{{ brand.id }}" ><span class="glyphicon glyphicon-trash"></span></button></p></td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    </div>
</div>
{% if request.user.is_superuser %}
<div class="modal fade" id="new" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
        <h4 class="modal-title custom_align" id="Heading">Nuevo Marca</h4>
    </div>
    <form class="form-horizontal" action="" autocomplete="off" method="POST">
        {% csrf_token %}
        <input type="hidden" name="action" value="CREATE">
        <div class="modal-body">
            {% for field in form %}
            {% if field.field.widget.is_hidden %}
            {{ field }}
            {% else %}
            <div class="form-group {% if field.errors %}has-error{% endif %}">
                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-10">
                    {{ field }}
                    {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-ok-sign"></span>Agregar</button>
            <button type="button" class="btn btn-default btn-lg" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancelar</button>
        </div>
    </form>
</div>
<div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
        <h4 class="modal-title custom_align" id="Heading">Borrar las marcas seleccionadas</h4>
    </div>
    <form class="form-horizontal" action="" method="POST" id="multi-delete">
        {% csrf_token %}
        <input type="hidden" name="brand_id" value="">
        <input type="hidden" name="action" value="DELETE">
        <div class="modal-body">
            <div class="alert alert-danger"><span class="glyphicon glyphicon-warning-sign"></span> Esta seguro de eliminar estas marcas de la base de datos?</div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-danger btn-lg" ><span class="glyphicon glyphicon-ok-sign"></span> Eliminar</button>
            <button type="button" class="btn btn-default btn-lg" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancelar</button>
        </div>
    </form>
</div>
{% for id, form in brand_forms.items %}
<div class="modal fade" id="edit{{ id }}" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
        <h4 class="modal-title custom_align" id="Heading">Actualizar marca</h4>
    </div>
    <form class="form-horizontal" action="" autocomplete="off" method="POST">
        {% csrf_token %}
        <input type="hidden" name="action" value="UPDATE">
        <div class="modal-body">
            {% for field in form %}
            {% if field.field.widget.is_hidden %}
            {{ field }}
            {% else %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-10">{{ field }}</div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-success btn-lg"><span class="glyphicon glyphicon-ok-sign"></span> Guardar</button>
            <button type="button" class="btn btn-default btn-lg" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancelar</button>
        </div>
    </form>
</div>
<div class="modal fade" id="delete{{ id }}" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
        <h4 class="modal-title custom_align" id="Heading">Borrar la marca</h4>
    </div>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="hidden" name="brand_id" value='["{{ id }}"]'>
        <input type="hidden" name="action" value="DELETE">
        <div class="modal-body">
            <div class="alert alert-danger"><span class="glyphicon glyphicon-warning-sign"></span> Esta seguro de eliminar esta marca de la base de datos?</div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-danger btn-lg" ><span class="glyphicon glyphicon-ok-sign"></span> Eliminar</button>
            <button type="button" class="btn btn-default btn-lg" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancelar</button>
        </div>
    </form>
</div>
{% endfor %}
{% endif %}

templates/sections/expensesReport.html
{% load custom_tags %}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <div class="row">
        <div class="panel panel-primary">
            <div class="panel-heading">
            <h3 class="panel-title">Revisar</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" action="." method="GET">
                    <div class="form-group">
                        <label for="exampleInputName2">Año</label>
                        <input type="number" class="form-control" name="year" value="{{ year }}" min="2000" max="2100">
                    </div>
                    {% if expenses_active.M %}
                    <div class="form-group">
                        <label for="exampleInputName2">Mes</label>
                        <input type="number" class="form-control" name="month" value="{{ month }}" min="1" max="12">
                    </div>
                    {% elif expenses_active.W %}
                    <div class="form-group">
                        <label for="exampleInputName2">Semana</label>
                        <input type="number" class="form-control" name="week" value="{{ week }}" min="1" max="52">
                    </div>
                    {% endif %}
                    <input type="hidden" name="time" value="{{ time }}">
                    <button type="submit" class="btn btn-default">Filtrar</button>
                </form>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="table-responsive">
            <table class="table table-bordred table-striped">
                <thead>
                    <tr>
                        <th>Fecha</th>
                        <th>Código</th>
                        <th>Nombre</th>
                        <th>Cantidad</th>
                        <th>Precio Unitario</th>
                        <th>Precio Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for input_reg in inputs %}
                        {% for product in input_reg.input_product_set.all %}
                        <tr>
                            <td>{{ input_reg.date.day }}-{{ input_reg.date.month|month_name }}-{{ input_reg.date.year }}</td>
                            <td>{{ product.product.code }}</td>
                            <td>{{ product.product.name }}</td>
                            <td>x {{ product.amount }}</td>
                            <td>${{ product.price }}</td>
                            <td>${{ product.amount|multiply:product.price }}</td>
                        </tr>
                        {% endfor %}
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="5" style="text-align: right;"><b>TOTAL</b></td>
                        <td><b>${{ inputs|total_sum }}</b></td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
<div>

templates/sections/productForm.html
<form class="form-horizontal" action="/" autocomplete="off" method="POST">
    {% csrf_token %}
    <input type="hidden" name="action" value="UPDATE">
    {% if storage %}
    <input type="hidden" name="storage" value="{{ storage }}">
    {% endif %}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}" class="col-xs-2 control-label">{{ field.label }}</label>
        <div class="col-xs-10">{{ field }}</div>
    </div>
    {% endfor %}
</form>

templates/sections/registryTable.html
{% load custom_tags %}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <div class="row">
        <div class="panel panel-primary">
            <div class="panel-heading">
            <h3 class="panel-title">Rango</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" action="." method="GET">
                  <div class="form-group">
                    <label for="exampleInputName2">Fecha inicio</label>
                    <input type="date" class="form-control" name="start_date" value="{{ formatted_start_date }}">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputEmail2">Fecha fin</label>
                    <input type="date" class="form-control" name="end_date" value="{{ formatted_end_date }}">
                  </div>
                  <button type="submit" class="btn btn-default">Filtrar</button>
                </form>
            </div>
        </div>
    </div>
    <div class="row">
        <h2>
            <div class="col-md-11 col-sm-10">Movimientos</div>
            <div class="col-md-1 col-sm-2">
                <p data-placement="top" data-toggle="tooltip" title="Eliminar reggistro seleccionadas"><button type="button" class="btn btn-danger btn-lg btn-block" data-toggle="modal" data-target="#delete"><i class="fa fa-trash"></i></button></p>
            </div>
        </h2>
    </div>
    <div class="row">
    <div class="table-responsive">
        <table class="table table-bordred table-striped">
            <thead>
                <th><input type="checkbox" id="checkall" /></th>
                <th>Fecha</th>
                <th>Tipo</th>
                <th>Productos</th>
                <th>Almacen</th>
                <th style="text-align: center;">Eliminar</th>
            </thead>
            <tbody>
                {% for reg in registry %}
                <tr>
                    <td><input type="checkbox" class="checkthis" value="{{ reg.id }}"/></td>
                    <td>{{ reg.date.day }}-{{ reg.date.month|month_name }}-{{ reg.date.year }}</td>
                    {% if reg.type == "Input" %}
                    <td>Entrada</td>
                    <td>
                        <table class="table table-bordred table-striped table-hover table-condensed">
                            <thead><tr><th>Código</th><th>Nombre</th><th>Cantidad</th></tr></thead>
                            <tbody>
                            {% for product in reg.input_product_set.all %}
                            <tr><td>{{ product.product.code }}</td><td>{{ product.product.name }}</td><td>{{ product.amount }}</td></tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </td>
                    {% elif reg.type == "Output" %}
                    <td>Salida</td>
                    <td>
                        <table class="table table-bordred table-striped table-hover table-condensed">
                            <thead><tr><th>Código</th><th>Nombre</th><th>Cantidad</th></tr></thead>
                            <tbody>
                            {% for product in reg.output_product_set.all %}
                            <tr><td>{{ product.product.code }}</td><td>{{ product.product.name }}</td><td>{{ product.amount }}</td></tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </td>
                    {% elif reg.type == "Lending" %}
                    <td>Prestamo</td>
                    <td>
                        <table class="table table-bordred table-striped table-hover table-condensed">
                            <thead><tr><th>Código</th><th>Nombre</th><th>Cantidad</th></tr></thead>
                            <tbody>
                            {% for product in reg.lending_product_set.all %}
                            <tr><td>{{ product.product.code }}</td><td>{{ product.product.name }}</td><td>{{ product.amount }}</td></tr>
                            {% endfor %}
                            {% for tool in reg.lending_tool_set.all %}
                            <tr><td>{{ tool.tool.code }}</td><td>{{ tool.tool.name }}</td><td>{{ tool.amount }}</td></tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </td>
                    {% endif %}
                    <td>{{ reg.get_storage_display }}</td>
                    <td align="center"><p data-placement="top" data-toggle="tooltip" title="Eliminar este registro"><button class="btn btn-danger" data-title="Delete" data-toggle="modal" data-target="#delete{{ reg.id }}" ><span class="glyphicon glyphicon-trash"></span></button></p></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    </div>
</div>

templates/sections/sidebar.html
<div class="col-sm-3 col-md-2 sidebar">
  {% if dashboard_active %}
  <ul class="nav nav-sidebar">
    <li class="{{ filter_active.all }}"><a href="/">Refacciones <span class="sr-only">(current)</span></a></li>
    <li class="{{ tools_active }}"><a href="/tools/">Herramientas</a></li>
    <li class="{{ providers_active }}"><a href="/providers/">Proveedores</a></li>
    <li class="{{ brands_active }}"><a href="/brands/">Marcas</a></li>
    <li class="{{ appliances_active }}"><a href="/appliances/">Aplicaciones</a></li>
    <li class="{{ percentages_active }}"><a href="/percentages/">Porcentajes</a></li>
    <li class="{{ organizations_active }}"><a href="/organizations/">Organizaciones</a></li>
  </ul>
  <ul class="nav nav-sidebar">
    <li><h5>Almacenes</h5></li>
    <li class="{{ filter_active.S }}"><a href="/?storage=S">Propias</a></li>
    <li class="{{ filter_active.C }}"><a href="/?storage=C">Consignación</a></li>
    <li class="{{ filter_active.U }}"><a href="/?storage=U">Obsoletas</a></li>
  </ul>
  <ul class="nav nav-sidebar">
    <li><h5>Movimientos</h5></li>
    <li class="{{ registry_active }}"><a href="/registry/">Todos</a></li>
    <li class="{{ inputs_active }}"><a href="/inputs/">Entradas</a></li>
    <li class="{{ outputs_active }}"><a href="/outputs/">Salidas</a></li>
    <li class="{{ lendings_active }}"><a href="/lendings/">Prestamos</a></li>
    <li class="{{ shopping_active }}"><a href="/shopping/">Pedidos</a></li>
  </ul>
  {% elif reports_active %}
  <ul class="nav nav-sidebar">
    <li class="{{ statistics_active }}"><a href="/reports/">Estadisticas</a></li>
  </ul>
  <ul class="nav nav-sidebar">
    <li><h5>Diferencias</h5></li>
    <li class="{{ product_diff_active }}"><a href="/reports/differences/products/">Productos</a></li>
    <li class="{{ provider_diff_active }}"><a href="/reports/differences/providers/">Proveedores</a></li>
    <li class="{{ storage_diff_active }}"><a href="/reports/differences/storage/">Almacenes</a></li>
  </ul>
  <ul class="nav nav-sidebar">
    <li><h5>Gastos</h5></li>
    <li class="{{ expenses_active.W }}"><a href="/reports/expenses/">Semanales</a></li>
    <li class="{{ expenses_active.M }}"><a href="/reports/expenses/?time=M">Mensuales</a></li>
    <li class="{{ expenses_active.A }}"><a href="/reports/expenses/?time=A">Anuales</a></li>
  </ul>
  {% endif %}
</div>